// <auto-generated />
using CodingCafe.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodingCafe.Migrations
{
    [DbContext(typeof(CafeContext))]
    [Migration("20231101162348_UpdateTables")]
    partial class UpdateTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CodingCafe.Models.Customers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FavoritesId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("FavoritesId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "jacksmith@gmail.com",
                            FavoritesId = 1,
                            FirstName = "Jack",
                            LastName = "Smith"
                        },
                        new
                        {
                            ID = 2,
                            Email = "jillsmith@gmail.com",
                            FavoritesId = 2,
                            FirstName = "Jill",
                            LastName = "Smith"
                        },
                        new
                        {
                            ID = 3,
                            FavoritesId = 3,
                            FirstName = "Steve",
                            LastName = "Jobs"
                        },
                        new
                        {
                            ID = 4,
                            FavoritesId = 4,
                            FirstName = "Bill",
                            LastName = "Gates"
                        });
                });

            modelBuilder.Entity("CodingCafe.Models.Favorites", b =>
                {
                    b.Property<int>("FavoritesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoritesId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FavoritesId");

                    b.ToTable("Favorites");

                    b.HasData(
                        new
                        {
                            FavoritesId = 1,
                            Description = "A dark, robust blend.",
                            Name = "Javascript Java"
                        },
                        new
                        {
                            FavoritesId = 2,
                            Description = "A light, decaf blend.",
                            Name = ".NET Decaf"
                        },
                        new
                        {
                            FavoritesId = 3,
                            Description = "Traditional hot chocolate, with whip!",
                            Name = "HTML Hot Cocoa"
                        },
                        new
                        {
                            FavoritesId = 4,
                            Description = "A tasty latte made with caramel and vanilla.",
                            Name = "LINQ Latte"
                        },
                        new
                        {
                            FavoritesId = 6,
                            Description = "A delicious hazelnut chai latte.",
                            Name = "Cyber Chai"
                        });
                });

            modelBuilder.Entity("CodingCafe.Models.Customers", b =>
                {
                    b.HasOne("CodingCafe.Models.Favorites", "Favorites")
                        .WithMany()
                        .HasForeignKey("FavoritesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
